---
- name: Install and Configure Nginx
  hosts: all
  become: yes
  tasks:
    - name: Updating the packages
      apt:
        update_cache: yes

    - name: Installing the Nginx
      apt:
        name: nginx
        state: present

    - name: Starting the Nginx
      service:
        name: nginx
        state: started
